import type { LegalDoc } from './types';

// Literal copy of https://www.caravelas.fit/teaser-politica-de-privacidade (old Wix site), 2026-10-09.
export const privacy: LegalDoc = {
  title: 'Política de Privacidade e Proteção de Dados',
  blocks: [
    { p: 'A CrossFit Caravelas está empenhada no cumprimento do Regulamento Geral sobre a Proteção de Dados (RGPD), assegurando a proteção de dados pessoais e reforçando a relação de confiança que a compromete com o cliente.' },
    { p: 'Esta Política de Privacidade e Proteção de Dados Pessoais consiste em prestar as informações que recolhemos e da forma como as podemos utilizar, bem como das normas de segurança adotadas para proteger a sua identidade e dados pessoais.' },
    { p: 'A CrossFit Caravelas reserva-se o direito de alterar a Política de Privacidade e Proteção de Dados Pessoais, pelo que o convida à consulta regular do presente documento.' },
    { p: 'Por favor note que a presente Política de Privacidade e Proteção de Dados Pessoais aplica-se a informação colhida pela CrossFit Caravelas apenas, e não se estende a informação que possa ter submetido em outros sites ou plataformas sociais geridas por outras entidades ou organizações.' },
    { h: '1. Responsável pelo tratamento de dados' },
    { p: 'FERNANDO OLIVEIRA & ANA DE LIMA - BEM ESTAR, LDA, BEM-ESTAR, NIPC 515.082.775,com sede Rua Hermano Neves, no 18, piso 3, E 7, Lisboa, 1600-477.' },
    { h: '2. Dados pessoais' },
    { p: 'Nos termos do RGPD, são considerados dados pessoais todas as informações relativas a uma pessoa singular identificada ou identificável (denominado o «titular dos dados»). É considerada identificável uma pessoa singular que possa ser identificada, direta ou indiretamente, em especial por referência a um identificador, como, por exemplo, nome, número de identificação, dados de localização, endereço IP (protocolo de internet), cookies, identificadores por via eletrónica ou a um ou mais elementos específicos da identidade física, fisiológica, genética, mental, económica, cultural ou social dessa pessoa singular.' },
    { p: 'Também constituem dados pessoais o conjunto de informações distintas que podem levar à identificação de uma determinada pessoa.' },
    { h: '3. Titular de dados pessoais' },
    { p: 'O titular de dados pessoais é a pessoa singular a quem os dados dizem respeito e que utilizou o site da CrossFit Caravelas.' },
    { h: '4. Categorias de dados pessoais e Finalidades' },
    { p: 'A CrossFit Caravelas recolhe diferentes categorias de dados:' },
    { ul: ['Nome;', 'Endereço de correio eletrónico;', 'Número de telefone;'] },
    { p: 'Os dados são recolhidos e tratados para diferentes finalidades. Entre outras, recolhemos e tratamos dados para o formulário de contacto, quando recebe ou envia mensagens de correio eletrónico e/ou quando subscreve serviços que exigem um registo, envio de convites para eventos da CrossFit Caravelas ou de entidades parceiras e identificação de visitantes, subscrição de newsletter e possíveis ações de marketing da CrossFit Caravelas, submissão de candidatura espontânea bem como para entrarmos em contacto consigo.' },
    { p: 'A CrossFit Caravelas, solicita o consentimento expresso do visitante do seu site antes de utilizar os dados pessoais para finalidades diferentes das previstas na presente Política de Privacidade e Proteção de Dados Pessoais.' },
    { p: 'Ao disponibilizar os seus dados pessoais à CrossFit Caravelas, o titular de dados pessoais autoriza que sejam tratados de acordo com a presente Política de Privacidade e Proteção de Dados Pessoais.' },
    { h: '5. Encarregado da Proteção de Dados' },
    { p: 'A CrossFit Caravelas tem um Encarregado da Proteção de Dados (EPD ou Data Protection Officer), cujas funções são informar e aconselhar o responsável pelo tratamento ou o subcontratante, bem como os seus trabalhadores, sobre as respetivas obrigações nos termos da lei da proteção de dados; controlar o cumprimento, por parte da organização, de toda a legislação relacionada com a proteção de dados, nomeadamente em auditorias, atividades de sensibilização e formação do pessoal implicado nas operações de tratamento; prestar aconselhamento sempre que tenha sido realizada uma avaliação de impacto de proteção de dados e controlar a sua realização; atuar como ponto de contacto para pedidos relativos ao tratamento dos seus dados pessoais, reclamações e exercício dos seus direitos; cooperar com a autoridade de controlo (Comissão Nacional de Proteção de Dados – CNPD) e atuar como ponto de contacto da mesma sobre questões relacionadas com o tratamento de dados pessoais.' },
    { p: 'O Encarregado da Proteção de Dados da CrossFit Caravelas pode ser contactado através do email feu.ferreira@caravelas.fit.' },
    { h: '6. Tempo e modo de conservação dos dados pessoais' },
    { p: 'A CrossFit Caravelas trata e conserva os seus dados pessoais conforme as finalidades para que os mesmos são recolhidos e tratados, e apenas pelo período de tempo necessário para o cumprimento das finalidades que motivaram a sua recolha.' },
    { p: 'Nos termos da lei, a CrossFit Caravelas, poderá ter de conservar os dados por um período de tempo mínimo: 1 ano, para os dados de tráfego e localização para efeitos de investigação, deteção e repressão de crimes graves; 10 anos, para informação à Autoridade Tributária para efeitos contabilísticos ou fiscais.' },
    { p: 'As informações que nos fornece ao visitar o nosso website estão protegidas no âmbito da implementação das várias medidas de segurança, nomeadamente, através de acesso condicionado e de salvaguarda da confidencialidade das informações.' },
    { p: 'Alertamos, contudo, que ao fornecer informações pessoais online, existe um risco de terceiros poderem intercetar e utilizar estas informações, o que em termos de segurança de qualquer informação que divulgue online, fará por sua própria conta e risco.' },
    { p: 'Para sua privacidade, aconselhamos que não inclua dados pessoais, nomeadamente sensíveis, ou e confidenciais nos emails que nos envia. Por favor, não nos envie via email números de cartão de crédito ou qualquer informação pessoal sensível.' },
    { p: 'Não recolhemos conscientemente informações pessoais de menores. Como pai/mãe ou responsável legal, não permita que os seus filhos enviem informações pessoais sem a sua permissão.' },
    { h: '7. Utilização de Cookies' },
    { p: 'Podemos usar tecnologias como "cookies" para registar informações de sessão, recolher visitas e aceder a detalhes da nossa página da web que nos permite continuar a melhorar os nossos serviços e fornecer melhores e mais úteis recursos aos usuários/ visitantes do nosso site.' },
    { p: 'Os cookies são peças de informação que são normalmente utilizadas por muitos sites para fins de manutenção de registos que podem ajudar a recordar, por exemplo, as suas preferências. Um cookie, por si só, não identifica pessoalmente nenhum usuário / visitante.' },
    { p: 'Caso pretenda, poderá descativar todos os cookies. Também pode fazer com que o seu computador o avise da utilização de cookies. Em ambos os casos, tem de ajustar as definições do seu navegador.' },
    { h: '8. Ligações de terceiros' },
    { p: 'Note, por favor, que apesar de se encontrar num website operado por nós, poderá também ser remetido para links para websites de terceiros. Estes sites de terceiros têm políticas de privacidade separadas e independentes. Estas políticas não são geridas nem controladas pela CrossFit Caravelas, pelo que não assumimos qualquer responsabilidade pelo conteúdo e atividades desses websites. No entanto, procuramos proteger a integridade do nosso site e das nossas plataformas e agradecemos que nos contacte caso queira dar-nos o seu feedback sobre os mesmos. Recomendamos, igualmente, que leia atentamente os termos e condições e as políticas de privacidade desses sites antes de submeter qualquer informação ou dados pessoais.' },
    { h: '9. O seu consentimento' },
    { p: 'Ao utilizar o nosso website concorda com nossa Política de Privacidade e Proteção de Dados.' },
    { h: '10. Direitos do titular de dados pessoais' },
    { p: 'Uma vez que queremos garantir que está consciente dos seus direitos e nos termos da legislação aplicável, queremos informá-lo que:' },
    { ul: [
      'Os seus dados pessoais pertencem-lhe a si. Como tal, tem o direito a aceder, retificar, limitar, apagar e opor-se ao tratamento dos mesmos assim como a obter os mesmos junto da CrossFit Caravelas',
      'Faremos todos os esforços para que os seus dados pessoais se mantenham atualizados e protegidos de acordo com os melhores standards praticados pela indústria.',
      'Tem o direito a apresentar uma queixa junto da autoridade de proteção de dados competente. Em Portugal, esta autoridade é a Comissão Nacional de Proteção de Dados (“CNPD”). Mais informação sobre a CNPD poderá ser obtida através do website www.cnpd.pt.',
      'Poderá retirar, a todo o tempo, o consentimento que tenha dado para o tratamento dos seus dados pessoais, no enquadramento do RGPD, o que não prejudica a licitude do tratamento dos dados pessoais que até aqui tenha sido efetuado, com base no consentimento que tenha previamente prestado.',
    ] },
    { h: '11. Contacte-nos' },
    { p: 'Em caso de dúvida sobre esta Política de Privacidade e Proteção de Dados Pessoais ou caso pretenda exercer qualquer um dos seus direitos referidos supra, por favor queira contactar-nos através de: feu.ferreira@caravelas.fit' },
  ],
};
